import { pgTable, serial, text, timestamp, boolean, integer } from "drizzle-orm/pg-core";

export const rosaUsers = pgTable("rosa_users", {
  id: serial("id").primaryKey(),
  emailOrPhone: text("email_or_phone").notNull().unique(),
  name: text("name").notNull(),
  stripeCustomerId: text("stripe_customer_id"),
  stripeSubscriptionId: text("stripe_subscription_id"),
  signupNumber: serial("signup_number"),
  isFoundingMember: boolean("is_founding_member").default(false),
  foundingMemberType: text("founding_member_type"),
  isLifetimeFree: boolean("is_lifetime_free").default(false),
  trialEndsAt: timestamp("trial_ends_at"),
  subscriptionStatus: text("subscription_status").default("trial"),
  partnerInviteCode: text("partner_invite_code"),
  partnerOfUserId: integer("partner_of_user_id"),
  tokenVersion: integer("token_version").notNull().default(1),
  marketingOptIn: text("marketing_opt_in").notNull().default("later"),
  anonymousName: text("anonymous_name").unique(),
  rosaId: text("rosa_id").unique(),
  nickname: text("nickname").unique(),
  nicknameChanges: integer("nickname_changes").notNull().default(0),
  bio: text("bio"),
  profilePhotoUrl: text("profile_photo_url"),
  accountType: text("account_type").default("public"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const trustedDevices = pgTable("trusted_devices", {
  id: serial("id").primaryKey(),
  email: text("email").notNull(),
  deviceId: text("device_id").notNull().unique(),
  deviceName: text("device_name"),
  userAgent: text("user_agent"),
  ipHash: text("ip_hash"),
  rememberMe: boolean("remember_me").notNull().default(false),
  expiresAt: timestamp("expires_at").notNull(),
  lastSeenAt: timestamp("last_seen_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
});
